version: '3.5'
services:
    backend:
        build: .
        restart: always
        command: npm run start:dev
        volumes:
            - .:/usr/app/
            - /usr/app/node_modules
        ports:
            - "3000:3000"
        depends_on: 
            - mongo
        environment:
            - HOST=mongo
            - PORT=27017
    mongo:
        image: mongo
        restart: always
        ports:  
            - "27017:27017"  
        volumes:
            - './data:/data/db'  